[phases.setup]
nixPkgs = [
    'nodejs_18',
    'chromium',
    'nss',
    'freetype',
    'harfbuzz',
    'ca-certificates',
    'ttf-freefont',
    'glib',
    'gtk3',
    'atk',
    'cairo',
    'pango',
    'gdk-pixbuf'
]

[phases.install]
cmds = [
    'npm ci --only=production',
    'ln -sf /nix/store/*/bin/chromium /usr/local/bin/google-chrome-stable || true'
]

[start]
cmd = 'cd whatsapp-bot && npm start'

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = 'true'
PUPPETEER_EXECUTABLE_PATH = '/usr/local/bin/google-chrome-stable'
